
public enum Place {
	//everything just has the name of whatever the name of the thing is . jpg
	//DONT FORGET THINGS TO SAY IN THE CONSOLE
	//REMEMBER THESE ARE TECHNICALLY NOT IN ANY ORDER
	HOMESCREEN, //0 BUTTON Play
	ADAFOREST1, //1 BUTTON Next
	ADAFOREST2, //2 BUTTON Back, BUTTON Next
	ADAFOREST3, //3 BUTTON Back, BUTTON Next
	ADASROOM, //4 CONSOLE "Click on the door to leave the room.", RECT(Door)
	ADASHOUSEINTERIOR, //5 *****************************
	ADASHOUSEEXTERIOR, //6 BUTTON To Forest, BUTTON Back Inside
	ADASFOREST,//************************
	ADASTREE, //**************************
	//ADAS HOUSE EXTERIOR BUTTON To Inside
	GOASKLIBRARIAN, //9 BUTTON
	TOWN1,//9 RECT(School), RECT(Town Hall), BUTTON(To Home), BUTTON(East Town), CONSOLE "Click on a building to go inside."
	TOWN2,//10 RECT(Grocery), RECT(Library), BUTTON(To Home), BUTTON(West Town), CONSOLE "Click on a building to go inside."
	LIBRARY,//11
	LIBRARIANTALK0,//12
	LIBRARIANTALK1,//13
	LIBRARIANTALK2,//14
	RECEIPT,//15
	LIBRARIANTALK3,//16
	BOOK1,//17
	BOOK2,//18
	BOOK3,//19
	BOOK4,//20
	BOOK5,//21
	SCHOOL,//22
	STUDICHTALK0,//23
	STUDICHTALK1,//24
	STUDICHTALK2,//25
	REUSABLECUP, //26
	STUDICHTALK3, //27
	GROCERY, //28
	GROCERTALK0, //29
	GROCERTALK1, //30
	GROCERTALK2, //31
	GROCERTALK3, //32
	APPLE, //33
	GROCERTALK4, //34
	GROCERTALK5, //35
	TOWNHALL, //36
	MAYORTALK0, //37
	MAYORTALK1, //38
	MAYORTALK2, //39
	MAYORTALK3, //40
	MAYORTALK4, //41
	DUMP, //42
	DUMPTALK0, //43
	DUMPTALK1, //44
	DUMPTALK2, //45
	
	
	
	
	
}
